### ISSUE TITLE
Dreamfactory with big tables doesn't work

### ISSUE THREAD

**Issue by PatrickHuetter** [dreamfactorysoftware/df-docker#1]
I'm using df-docker to create a rest service / api for a mysql database. This works fine but i have big problems with one table within this database. This table contains 1.7 million rows. I don't get any result from the rest service querying this table. It's also not possible to view this table within "Data" view in backend. Viewing schema in backend is possible without problems. Are 1.7 million rows too much for dreamfactory or is this a bug?

**Comment by todda48** [comment]
You should use the pagination features of the API with datasets of this size. You can set query params like limit, offset, include_count=true.

**Comment by PatrickHuetter** [comment]
I already did this. Limiting doesn't have effect on the result. It stays empty/blank. Using dreamfactory 1.9.x with the same setup and datasource works perfect.

**Comment by todda48** [comment]
Do the logs show anything? For 2.0 you have to include API key not app
name, and session token. Send me the full request and response including
headers if you can. If you are not accessing as an admin user, does the
user's role allow access to the table?

**Comment by PatrickHuetter** [comment]
I can't reproduce the issue because we aren't using DF 2.0 anymore (we downgraded). Just for your information: We used the API key and were able to query other tables without problems. The problem occured only with this one special table. We checked the roles three times and they allowed all access.
