### ISSUE TITLE
DF Container immediately dies on restart

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/df-docker#11]
I went with "Configuration Method 3 (Build your own)" as I had to hook up DF to an external MySQL.
So all I changed was https://github.com/dreamfactorysoftware/df-docker/blob/master/Dockerfile#L39  and appended `--db_host=blabla.eu-central-1.rds.amazonaws.com --db_password=foobar`
Then run the container with `docker run -d -p 80:80 dreamfactory/v2`, worked like a charm. 
I configured users, services, app etc..
Now I stopped the container and wanted to start it again to verify everything is persisted (should be as everything is stored in the external DB), however to my surprise, the container exits immediately.

~~As a second test I created a new container based on the image. It again started, however was messed up. The welcome page was empty and the services were not listed although present in the DB. Also "API Docs" _does_ see the services.
But a restart of that container didnt work either.~~ due to a second bug -> https://github.com/dreamfactorysoftware/df-docker/issues/13

(There also a support case open Case #: 413)

**Comment by philicious** [comment]
Bump.
You really should fix this as df-docker is fundamentally broken since https://github.com/dreamfactorysoftware/df-docker/commit/6fc02a457d54d7cf0c7495748dd628e3602ce877 and so is the image on Docker Hub!

**Comment by todda48** [comment]
Working on this.

**Comment by philicious** [comment]
fixed and merged with #22
