### ISSUE TITLE
ubuntu:latest no longer supports php5 (as of 16.06)

### ISSUE THREAD

**Issue by cjeffers** [dreamfactorysoftware/df-docker#16]
`docker-compose build` fails at `apt-get install php5` (and other `php5` packages) with the following error:

```
Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5' has no installation candidate
```

[This ask ubuntu post](http://askubuntu.com/questions/756181/installing-php-5-6-on-xenial-16-04) has instructions that involve adding a separate PPA (ondrej/php) which, when I tried, had some cert issues.

I was able to resolve the issue simply by changing the Dockerfile to start with `FROM ubuntu:trusty`. Since Trusty is the latest LTS which supports php5, I thought it would be a good place to go. The other option would be to change all the php dependencies to php 7, which may not be possible for a variety of reasons.

I would be happy to open a PR regarding this, but thought it was minor enough that an issue would be good to start with.

Thoughts?

**Comment by todda48** [comment]
A PR would be great. Thanks!
