### ISSUE TITLE
Api Error

### ISSUE THREAD

**Issue by bkcummins** [dreamfactorysoftware/df-docker#2]
I'm installing DF off the dreamfactorysoftware/df-docker image.

It runs fine. I'm able to login, create roles, services, etc.

But when I try to follow the Angular SDK example I cannot complete the setup tasks.
https://github.com/dreamfactorysoftware/angular-sdk

There appears to be issues with DF's sql statements.

For example, when I go to CORS set Origin, Paths, and Headers to *, set Max Age to 0, allow all HTTP verbs, check the Enabled box, and click update I get the following.

Api Error
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: cors_config.created_date (SQL: insert into "cors_config" ("origin", "path", "method", "enabled", "header", "max_age", "created_by_id") values (*, *, 1, 1, *, 0, 1))

Any ideas?

**Comment by drewpearce** [comment]
This is actually not an issue with the docker package but with DF itself. There's an issue with saving CORS configs when using SQLite as the system db. If you switch to MySQL this issue is not present. http://wiki.dreamfactory.com/DreamFactory/Installation#Switch_System_Database
