### ISSUE TITLE
Redirect dreamfactory.log to docker logging driver

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/df-docker#29]
@df-arif I wanted to send the dreamfactory.log to a central logging server. 
However you cannot ln it to stdout which is working fine for the 
`RUN ln -sf /dev/stderr /var/log/apache2/error.log` 

If you try this with the dramfactory.log you get this error
```
500 : {"error":{"context":null,"message":"The stream or file &quot;/opt/dreamfactory/storage/logs/dreamfactory.log&quot; could not be opened: failed to open stream: No such file or directory","code":500,"trace":["0 /opt/dreamfactory/vendor/dreamfactory/df-core/src/LogHandlers/DfLoggingTrait.php
....
```
..which can happen as the ln trick doesnt work for all sorts of applications depending on how they operate on the given file.

So what DOES work however, is having near end of `docker-entrypoint.sh` just before the `exec ..`
```
# we cannot ln the log to stdout like with apache logs, so we continuously tail it
tail --pid $$ -F /opt/dreamfactory/storage/logs/dreamfactory.log &
```

If you like, I could PR this. Probably if-wrapped with some env var like `LOG_TO_STDOUT`

PS:
I'm wondering about log format 'single', 'daily', 'syslog', and 'errorlog' ?
If I should guess, I'd say they map to https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md

So I assume
- "daily" ->  RotatingFileHandler
- "syslog" -> SyslogHandler
- "errorlog" ->ErrorLogHandler
- "single" -> StreamHandler ???

**Comment by a15lam** [comment]
@philicious, feel free to make a PR with an env var like LOG_TO_STDOUT as you suggested. 

Yes, you are right about your assumption on log file handlers. This is all handled by Laravel which uses Monolog.

**Comment by df-arif** [comment]
@philicious, feel free to make a PR with an env var like LOG_TO_STDOUT as you suggested.

Yes, you are right about your assumption on log file handlers. This is all handled by Laravel which uses Monolog.

**Comment by philicious** [comment]
see PR #30
