### ISSUE TITLE
Configuration method 1, where is the data?

### ISSUE THREAD

**Issue by HavardLine** [dreamfactorysoftware/df-docker#32]
Hi There! We implement df-docker locally. I am in the process of finding out what data we should keep when swapping out containers.

mysql: /var/lib/mysql **-OK**
redis: nothing? **-NEED TO CONFIRM**
df-docker: nothing? **-NEED TO CONFIRM**

Are anyone able to help us out here?

**This is our current code**
df1-db.service, df1-redis.service and df1.service can be found at [https://github.com/LTS-AS/CoreOS/tree/master/fleet](https://github.com/LTS-AS/CoreOS/tree/master/fleet)

**Comment by HavardLine** [comment]
OK, we KNOW that we need this data

**mysql:**
DB data at /var/lib/mysql

**df-docker:**
Local file service at /opt/dreamfactory/storage/app/

There may be other places.

**Comment by idnow-philicious** [comment]
@HavardLine I'm running DF as immutable container(s) and all you need to care about for preserving data is 

- MySQL: if its a linked container, you need to "volume" `/var/lib/mysql`
- Dreamfactory: if you have a local app then volume `/opt/dreamfactory/storage/app/` and if you use the "db" service (SQLite) then also `/opt/dreamfactory/storage/databases/`

I see you are using fleet for orchestration. I wrote a few blog posts that might interest you but they use docker-compose
http://www.devops-blog.net/dreamfactory/using-dreamfactory-2-x-as-rest-api-with-docker
http://www.devops-blog.net/dreamfactory/orchestrating-dreamfactory-with-docker-compose-and-a-loadbalancer

**Comment by philicious** [comment]
@HavardLine I'm running DF as immutable container(s) and all you need to care about for preserving data is

- MySQL: if its a linked container, you need to "volume" /var/lib/mysql
- Dreamfactory: if you have a local app then volume /opt/dreamfactory/storage/app/ and if you use the "db" service (SQLite) then also /opt/dreamfactory/storage/databases/

I see you are using fleet for orchestration. I wrote a few blog posts that might interest you but they use docker-compose
http://www.devops-blog.net/dreamfactory/using-dreamfactory-2-x-as-rest-api-with-docker
http://www.devops-blog.net/dreamfactory/orchestrating-dreamfactory-with-docker-compose-and-a-loadbalancer

**Comment by HavardLine** [comment]
Perfect! thanks @philicious
