### ISSUE TITLE
How to gracefully stop and start docker container

### ISSUE THREAD

**Issue by Zlatokosa** [dreamfactorysoftware/df-docker#36]
I have dreamfactory container set by docker-compose. 
Everything worked correctly until I had to restart my local machine. Afterwards, dreamfactory container got status "Exited", while redis and mysql container are up and works fine.
How to properly start and stop dreamfactory container?
Also, if I remove containers, and run the new ones, everything works, but Data and Schema in web portal are empty. 
Could you please also tell me where these files are kept.
I suppose then it is inside container?

Thank you for your help.

**Comment by HavardLine** [comment]
Hi @Zlatokosa

I have newer tried docker-compose before. Anyway, we have experienced related issues. This is what we have figured out that we need to get Dreamfactory up an running after swapping containers.

- You need to set your unique and random APP_KEY in your web-environment. Seems like it needs to be 16 or 32 BASE64-characters. Not realy shure what APP_KEY does.
- Local file storage service in the web-container:
/opt/dreamfactory/storage/app
- Local SQLite database services in the web-container:
/opt/dreamfactory/storage/databases

**Comment by philicious** [comment]
only see this now, have a look at my articles that also explains the issue with APP_KEY and how to use it with docker-compose http://www.devops-blog.net/category/dreamfactory
