### ISSUE TITLE
Issue in 0863cd9?

### ISSUE THREAD

**Issue by HavardLine** [dreamfactorysoftware/df-docker#39]
Hi There, seems like 0863cd9 has inplications for users with unspecified DB_PORT

**Comment by a15lam** [comment]
Thanks for bringing this up. I will get this fixed. In the meantime you can use the 2.5.0 branch for DF 2.5.0. This branch doesn't have the latest commit.

**Comment by df-arif** [comment]
Thanks for bringing this up. I will get this fixed. In the meantime you can use the 2.5.0 branch for DF 2.5.0. This branch doesn't have the latest commit.

**Comment by HavardLine** [comment]
OK! Thanks for the advice @df-arif
