### ISSUE TITLE
Map server to different port

### ISSUE THREAD

**Issue by hydrosquall** [dreamfactorysoftware/df-docker#4]
Hi,

On my server, internal port 127.0.0.1:80 is mapped to another service so I can't use it. I looked at the .env file and couldn't figure out how to connect to a different port - is there a way to do this?

**Comment by mohan08p** [comment]
I think, we can manually assign the different port while mapping container port(internal port) to the global port...also known as network port binding. Even same with the URL if its not local-host environment...

**Comment by HavardLine** [comment]
Hi @hydrosquall 

I realize that this is a old post. Anyway here is a suggestion for how to expose host port 8080.

The suggestion is for "Configuration method 1" in the README.

`docker run -d --name df-web -p 127.0.0.1:8080:80 -e "DB_HOST=db" -e "DB_USERNAME=df_admin" -e "DB_PASSWORD=df_admin" -e "DB_DATABASE=dreamfactory" -e "REDIS_HOST=rd" -e "REDIS_DATABASE=0" -e "REDIS_PORT=6379" --link df-mysql:db --link df-redis:rd dreamfactorysoftware/df-docker`
