### ISSUE TITLE
Docker build fails on df:setup

### ISSUE THREAD

**Issue by zorel** [dreamfactorysoftware/df-docker#41]
docker build fails on this line:

`RUN php artisan df:setup --no-app-key --db_connection=sqlite --df_install=Docker`

Displays:
`The "--db_connection" option does not exist.`

**Comment by leehicks** [comment]
This is due to environment and setup changes in the latest build. Please refer to [DockerHub](https://hub.docker.com/r/dreamfactorysoftware/df-docker/) for the latest working version with DreamFactory 2.7.0.
