### ISSUE TITLE
Perhaps Missing php dependencies for dreamfactory version 2.12.0 ?

### ISSUE THREAD

**Issue by rantheman** [dreamfactorysoftware/df-docker#44]
Trying to build container for dreamfactory version 2.12.0 with the provided Dockerfile results in the following error. (Note that the build worked fine for DF version 2.10.0) 

> Loading composer repositories with package information
> Installing dependencies from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for php-amqplib/php-amqplib v2.7.2 -> satisfiable by php-amqplib/php-amqplib[v2.7.2].
>     - php-amqplib/php-amqplib v2.7.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
>   Problem 2
>     - Installation request for yajra/laravel-oci8 v5.5.8 -> satisfiable by yajra/laravel-oci8[v5.5.8].
>     - yajra/laravel-oci8 v5.5.8 requires ext-oci8 >=2.0.0 -> the requested PHP extension oci8 is missing from your system.
>   Problem 3
>     - php-amqplib/php-amqplib v2.7.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
>     - dreamfactory/df-amqp 0.1.0 requires php-amqplib/php-amqplib 2.7.* -> satisfiable by php-amqplib/php-amqplib[v2.7.2].
>     - Installation request for dreamfactory/df-amqp 0.1.0 -> satisfiable by dreamfactory/df-amqp[0.1.0].

Had to install install php7.1-bcmath and php oci8 extension for the container build process to work. Changes in dockerfile below: 
> RUN apt-get install -y php7.1-bcmath
> RUN apt-get update -qq
> RUN apt-get install -y unzip libaio1
> RUN mkdir -p /opt/oracle
> RUN wget https://github.com/bumpx/oracle-instantclient/raw/master/instantclient-basic-linux.x64-12.1.0.2.0.zip
> RUN wget https://github.com/bumpx/oracle-instantclient/raw/master/instantclient-sdk-linux.x64-12.1.0.2.0.zip
> RUN unzip -o ./instantclient-basic-linux.x64-12.1.0.2.0.zip -d /opt/oracle
> RUN unzip -o ./instantclient-sdk-linux.x64-12.1.0.2.0.zip -d /opt/oracle
> RUN ln -s /opt/oracle/instantclient/sqlplus /usr/bin/sqlplus
> RUN ln -s /opt/oracle/instantclient_12_1 /opt/oracle/instantclient
> RUN ln -s /opt/oracle/instantclient/libclntsh.so.12.1 /opt/oracle/instantclient/libclntsh.so
> RUN ln -s /opt/oracle/instantclient/libocci.so.12.1 /opt/oracle/instantclient/libocci.so
> RUN pecl channel-update pecl.php.net
> RUN echo 'instantclient,/opt/oracle/instantclient' | pecl install oci8
> RUN echo "extension = oci8.so" >> /etc/php/7.1/fpm/php.ini
> RUN echo "extension = oci8.so" >> /etc/php/7.1/cli/php.ini

**Comment by drewpearce** [comment]
I just submitted a pull request for bcmath.

oci8 is not required except by the silver and gold versions of DreamFactory. This repo is only scoped for the open source version. Additionally, the Oracle instant client requires downloading from a registered user and is thus not appropriate for us to include in this public repo.
