### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by maitrepylos** [dreamfactorysoftware/df-docker#5]
Hello, I made the installation following the documentation, but I do not manage to launch the application.

Here is my docker-compose.yml : 

dreamfactory:
  environment:
    SERVERNAME: dreamfactory.local
  build: .
  volumes:
        - ./.env:/opt/dreamfactory/.env
  links:
         - db:db
  ports:
        - "80:80"
db:
        image: webhippie/mariadb:latest
        ports:
                 - "3306:3306"
        volumes:
                 - /opt/docker/mariadb/log:/var/log/mysql
                 - /opt/docker/mariadb/data:/var/lib/mysql
        environment:
                MARIADB_ROOT_PASSWORD: bonjour

**Comment by flaviostutz** [comment]
I managed to overcome this issue. Check my pull request on README.md.
